[build]
  command = "npm run build"
  publish = "build"

# Si quieres mapear /api/* a funciones, usa reglas de redirect. Aquí usamos las funciones directas en /.netlify/functions/*
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
